"""
Django settings for mydemo project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
HOME_DIR = Path.home()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wv@c1u*_(!%62!kh(oqzm1l876cuaa1c^22jc25kgx^313g+3y'

ALLOWED_HOSTS = ["*"]  # "*" for test only

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'health_check',
    'annotation'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coevoloop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            str(BASE_DIR.parent / 'viewer' / 'dist'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coevoloop.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    str(BASE_DIR.parent / 'resource'),
    str(BASE_DIR.parent.parent / 'viewer' / 'dist'),
]
STATIC_ROOT = str(BASE_DIR.parent.parent / 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# BASE_LOG_DIR
BASE_LOG_DIR = HOME_DIR / 'logs'/ 'coevoloop'

# 日志文件路径
APP_DEFAULT_LOG_FILE = BASE_LOG_DIR / 'app-default.log'
APP_ERROR_LOG_FILE = BASE_LOG_DIR / 'common-error.log'
FINTL_LOG_FILE = BASE_LOG_DIR / 'fintl.log'
os.environ["FINTL_LOG_FILE"] = str(FINTL_LOG_FILE)


# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    "formatters": {
        "antdefault": {
            "format": "%(asctime)s %(levelname)s %(name)s:%(lineno)d - %(message)s"
        },
        "simple": {
            "format": "%(asctime)s %(levelname)s %(name)s:%(lineno)d - %(message)s"
        }
    },
    # handler改成TimedRotatingFileHandler
    "handlers": {
        "file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(APP_DEFAULT_LOG_FILE),
            "formatter": "antdefault",
            "level": "INFO",
            "when": "midnight",
            "interval": 1,
            "backupCount": 5,
            "encoding": "utf-8"
        },
        "error": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": str(APP_ERROR_LOG_FILE),
            "formatter": "antdefault",
            "level": "ERROR",
            "when": "midnight",
            "interval": 1,
            "backupCount": 5,
            "encoding": "utf-8"
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "antdefault",
        }
    },
    "loggers": {
        "demoapp": {
            "handlers": ["file", "console", "error"],
            "level": "INFO",
            "propagate": True,
        },
        "coevoloop": {
            "handlers": ["file", "console", "error"],
            "level": "INFO",
            "propagate": True,
        },
         "django": {
            "handlers": ["file", "console", "error"],
            "level": "ERROR",
            "propagate": True,
        }
    }
}

# CORS settings - 允许所有来源（开发环境）
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# 如果需要限制特定来源，可以使用以下配置替代CORS_ALLOW_ALL_ORIGINS
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:8080",
#     "http://127.0.0.1:8080",
#     "http://30.182.217.229:8080",
# ]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}